// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCtf-sSpVFUxUVdVeTTROBAYnDzN_djN0',
    appId: '1:370213494932:web:40be500f4e496d908fd481',
    messagingSenderId: '370213494932',
    projectId: 'flutter-f6a64',
    authDomain: 'flutter-f6a64.firebaseapp.com',
    storageBucket: 'flutter-f6a64.firebasestorage.app',
    measurementId: 'G-TX15RDJEQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCMbtknJ4EdRJ2Q6rtOQj-vm0goUhIrw8',
    appId: '1:370213494932:android:ce797a1c8ea501e98fd481',
    messagingSenderId: '370213494932',
    projectId: 'flutter-f6a64',
    storageBucket: 'flutter-f6a64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqNscr0hPOQqmb6ndJVC0BWIsLAOL8C2c',
    appId: '1:370213494932:ios:7b6e9478132f64f68fd481',
    messagingSenderId: '370213494932',
    projectId: 'flutter-f6a64',
    storageBucket: 'flutter-f6a64.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqNscr0hPOQqmb6ndJVC0BWIsLAOL8C2c',
    appId: '1:370213494932:ios:7b6e9478132f64f68fd481',
    messagingSenderId: '370213494932',
    projectId: 'flutter-f6a64',
    storageBucket: 'flutter-f6a64.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCtf-sSpVFUxUVdVeTTROBAYnDzN_djN0',
    appId: '1:370213494932:web:88803706d1af7b508fd481',
    messagingSenderId: '370213494932',
    projectId: 'flutter-f6a64',
    authDomain: 'flutter-f6a64.firebaseapp.com',
    storageBucket: 'flutter-f6a64.firebasestorage.app',
    measurementId: 'G-30VM845TJZ',
  );
}
